export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const CREATE_PRODUCT_IMAGES_SUCCESS = 'CREATE_PRODUCT_IMAGES_SUCCESS';
export const DELETE_PRODUCT_IMAGES_SUCCESS = 'DELETE_PRODUCT_IMAGES_SUCCESS';
