export const LOAD_HOTWORDS_SUCCESS = 'LOAD_HOTWORDS_SUCCESS';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_SALEPRODUCT_SUCCESS = 'LOAD_SALEPRODUCT_SUCCESS';
export const LOAD_POPULAR_PRODUCT_SUCCESS = 'LOAD_POPULAR_PRODUCT_SUCCESS';
export const LOAD_MALLS_SUCCESS = 'LOAD_MALLS_SUCCESS';
export const LOAD_SINGLE_PRODUCT_IMEGESUCCESS = 'LOAD_SINGLE_PRODUCT_IMEGESUCCESS';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
