export const LOAD_HOTWORDS_SUCCESS = 'LOAD_HOTWORDS_SUCCESS';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const LOAD_PRODUCT_SUCCESS = 'LOAD_PRODUCT_SUCCESS';
export const LOAD_SALEPRODUCT_SUCCESS = 'LOAD_SALEPRODUCT_SUCCESS';
export const LOAD_POPULAR_PRODUCT_SUCCESS = 'LOAD_POPULAR_PRODUCT_SUCCESS';
export const LOAD_MALLS_SUCCESS = 'LOAD_MALLS_SUCCESS';
export const LOAD_SINGLE_PRODUCT_IMEGESUCCESS = 'LOAD_SINGLE_PRODUCT_IMEGESUCCESS';
export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const ADD_ITEM_TO_SHOPID = 'ADD_ITEM_TO_SHOPID';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';


export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const END_AJAX_CALL = 'END_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';


export const LOAD_G_CATEGORIES_SUCCESS = 'LOAD_G_CATEGORIES_SUCCESS';
